# Same as Black.
line-length = 80
indent-width = 4

# Assume Python 3.8
target-version = "py312"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = ["E4", "E7", "E9", "F"]